# SPDX-License-Identifier: Apache-2.0
# Author: Robert Balas (balasr@iis.ee.ethz.ch)

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pwd
  - export RISCV=~balasr/.riscv

stages:
  - fetch
  - test

fetch_gcc:
  stage: fetch
  tags:
    - dolent1
  script:
    - echo "FIXME using balasr hardcoded path"

fetch_pulp:
  stage: fetch
  tags:
    - dolent1
  script:
     - git clone https://github.com/pulp-platform/pulp
     - cd pulp
     # latest "stable" version
     - git checkout 75cc0947d85cd86e63b499f5465fd054fa795e5a
     - ./update-ips
     - ./generate-scripts --rt-dpi
     - make build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - pulp/*

test_demos:
  stage: test
  tags:
    - dolent1
  script:
    - echo "FIXME run demos tests"

test_apps:
  stage: test
  tags:
    - dolent1
  script:
    - echo "FIXME add app tests"

vsim_pulp_semaphore:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - source pulp/setup/vsim.sh
    - cd tests/semaphore
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
     - tests/semaphore

vsim_pulp_queue:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - source pulp/setup/vsim.sh
    - cd tests/queue
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/queue

vsim_pulp_streambufferisr:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - source pulp/setup/vsim.sh
    - cd tests/streambufferisr
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/streambufferisr

vsim_pulp_uart:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - source pulp/setup/vsim.sh
    - cd tests/uart
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/uart

vsim_pulp_hello_world_pmsis:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - source pulp/setup/vsim.sh
    - cd tests/hello_world_pmsis
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/hello_world_pmsis

vsim_pulp_spi:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - source pulp/setup/vsim.sh
    - cd tests/spi
    - make clean all run DPI=yes
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/spi

gvsoc_pulp_hello_world:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - cd nortos/hello_world
    - make clean all run-gvsoc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - nortos/hello_world

gvsoc_pulp_setjmp:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - cd nortos/setjmp
    - make clean all run-gvsoc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - nortos/setjmp

gvsoc_pulp_uart:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - cd tests/uart
    - make clean all run-gvsoc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/uart

gvsoc_pulp_semaphore:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - cd tests/semaphore
    - make clean all run-gvsoc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
     - tests/semaphore

gvsoc_pulp_queue:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - cd tests/queue
    - make clean all run-gvsoc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/queue

gvsoc_pulp_streambufferisr:
  stage: test
  tags:
    - dolent1
  script:
    - source env/pulp.sh
    - cd tests/streambufferisr
    - make clean all run-gvsoc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - tests/streambufferisr
