# SPDX-License-Identifier: Apache-2.0
# Author: Robert Balas (balasr@iis.ee.ethz.ch)

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pwd
  - export RISCV=~balasr/.riscv

stages:
  - fetch
  - test

fetch_gcc:
  stage: fetch
  tags:
    - dolent1
  script:
    - echo "FIXME using balasr hardcoded path"

fetch_pulp:
  stage: fetch
  tags:
    - dolent1
  script:
     - git clone https://github.com/pulp-platform/pulp
     - cd pulp
     # latest "stable" version
     - git checkout 75cc0947d85cd86e63b499f5465fd054fa795e5a
     - ./update-ips
     - ./generate-scripts --rt-dpi
     - make build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - pulp/*

test_demos:
  stage: test
  tags:
    - dolent1
  script:
    - echo "FIXME run demos tests"

test_apps:
  stage: test
  tags:
    - dolent1
  script:
    - echo "FIXME add app tests"

test_semaphore:
  stage: test
  tags:
    - dolent1
  script:
    - source pulp/setup/vsim.sh
    - cd RISC-V_PULP_Project/tests/semaphore
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
     - RISC-V_PULP_Project/tests/semaphore

test_queue:
  stage: test
  tags:
    - dolent1
  script:
    - source pulp/setup/vsim.sh
    - cd RISC-V_PULP_Project/tests/queue
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - RISC-V_PULP_Project/tests/queue

test_streambufferisr:
  stage: test
  tags:
    - dolent1
  script:
    - source pulp/setup/vsim.sh
    - cd RISC-V_PULP_Project/tests/streambufferisr
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - RISC-V_PULP_Project/tests/streambufferisr

test_uart:
  stage: test
  tags:
    - dolent1
  script:
    - source pulp/setup/vsim.sh
    - cd RISC-V_PULP_Project/tests/uart
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - RISC-V_PULP_Project/tests/uart

test_hello_world_pmsis:
  stage: test
  tags:
    - dolent1
  script:
    - source pulp/setup/vsim.sh
    - cd RISC-V_PULP_Project/tests/hello_world_pmsis
    - make clean all run
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - RISC-V_PULP_Project/tests/hello_world_pmsis

test_spi:
  stage: test
  tags:
    - dolent1
  script:
    - source pulp/setup/vsim.sh
    - cd RISC-V_PULP_Project/tests/spi
    - make clean all run DPI=yes
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - RISC-V_PULP_Project/tests/spi

gvsoc_hello_world:
  stage: test
  tags:
    - dolent1
  script:
    - cd RISC-V_PULP_Project/nortos/hello_world
    - make clean all run-gvsoc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - RISC-V_PULP_Project/nortos/hello_world
